import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { fileURLToPath } from 'node:url';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';

export async function startFixture(port, overrides = {}) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'taskbridge-http-test-'));
  const repo = fileURLToPath(new URL('..', import.meta.url));
  await fs.cp(path.join(repo, 'src'), path.join(root, 'src'), { recursive: true });
  await fs.cp(path.join(repo, 'web'), path.join(root, 'web'), { recursive: true });
  await fs.copyFile(new URL('fake-pi.mjs', import.meta.url), path.join(root, 'fake-pi.mjs'));
  const command = path.join(root, process.platform === 'win32' ? 'pi.cmd' : 'pi');
  await fs.writeFile(command, process.platform === 'win32' ? `@echo off\r\nnode "${path.join(root, 'fake-pi.mjs')}" %*\r\n` : `#!/bin/sh\nexec node '${path.join(root, 'fake-pi.mjs')}' "$@"\n`, { mode: 0o755 });
  if (!port) {
    const probe = net.createServer();
    await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve));
    port = probe.address().port;
    await new Promise(resolve => probe.close(resolve));
  }
  await fs.writeFile(path.join(root, 'config.json'), JSON.stringify({
    server: { host: '127.0.0.1', port, ...(overrides.server || {}) },
    pi: { command, projectTrust: 'deny' },
    localRuntime: {},
    projects: [{ id: 'fixture', name: 'Тестовая сессия', path: root, useWorktree: false }],
    ...(overrides.root || {})
  }));
  let logs = '';
  const launch = () => {
    const child = spawn(process.execPath, ['src/server.mjs'], { cwd: root, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
    child.stdout.on('data', data => { logs += data; });
    child.stderr.on('data', data => { logs += data; });
    return child;
  };
  let proc = launch();
  const base = `http://127.0.0.1:${port}`;
  const api = async (route, body, method) => {
    const response = await fetch(base + route, { method: method || (body ? 'POST' : 'GET'), ...(body ? { body: JSON.stringify(body), headers: { 'content-type': 'application/json' } } : {}) });
    const data = await response.json();
    if (!response.ok) throw Object.assign(new Error(data.error), { code: data.code, status: response.status });
    return data;
  };
  const waitReady = async () => {
  let ready = false;
  for (let i = 0; i < 100; i++) {
    try { await api('/api/health'); ready = true; break; } catch {}
    await new Promise(resolve => setTimeout(resolve, 30));
  }
  if (!ready) throw new Error(`Fixture startup failed: ${logs}`);
  };
  const stop = async () => {
    if (process.platform === 'win32') await promisify(execFile)('taskkill', ['/PID', String(proc.pid), '/T', '/F'], { windowsHide: true }).catch(() => {});
    else proc.kill();
    if (proc.exitCode === null) await new Promise(resolve => proc.once('close', resolve));
  };
  await waitReady();
  return { base, root, api, logs: () => logs, restart: async () => { await stop(); proc = launch(); await waitReady(); }, close: async () => {
    await stop();
    // root is generated by mkdtemp under the system temp directory above.
    if (path.dirname(root) !== path.resolve(os.tmpdir()) || !path.basename(root).startsWith('taskbridge-http-test-')) throw new Error('Invalid fixture cleanup root');
    await fs.rm(root, { recursive: true, force: true });
  } };
}

if (process.argv.includes('--serve')) {
  const fixture = await startFixture(8788);
  console.log(`Fixture UI: ${fixture.base}`);
  for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, async () => { await fixture.close(); process.exit(); });
}
